version: "3.7"

services:
  web:
    build: ./flaskapp
    container_name: flask
    entrypoint: gunicorn -b 0.0.0.0:8000 app:app
    ports: 
      - "8000:8000"
    links:
      - mongodb
    restart:  always
  
  nginx:
    build: ./nginx
    container_name: nginx
    network_mode: "host"
    ports:
      - "80:80"
    restart:  always

  cache:
    image: redis
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart:  always

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=test
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  redis_data:
  mongo_data: