version: "3.7"

services:
  web:
    build: ./flaskapp
    container_name: flask
    entrypoint: gunicorn -b 0.0.0.0:8000 app:app
    ports: 
      - "8000:8000"
  
  nginx:
    build: ./nginx
    container_name: nginx
    network_mode: "host"
    ports:
      - "80:80"